config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
#このルーティングにより、ToppagesControllerとindexアクション、toppages/index.html.erbが必要となる
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  
  resources :users, only: [:index, :show, :new, :create] do
          #ユーザ登録用ルーティング
          #この後uesrscontrollerを作成する
          # command///rails g controller users index show new create
    member do
      get :followings
      get :followers
      get :favoritings
    end
  end
  # フォロー中のユーザ・フォローされているユーザ一覧表示するページのためのルーティング
  # URLを深掘りするresourcesオプション・member/collection
  # memberはid特定する必要があるか
  

  resources :newmicroposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
# 中間テーブルはユーザには見せない・viewでボタンを設置する
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  #パスワード付きのモデル作成時に使用
  #Rails標準機能
  
  has_many :newmicroposts
  # 一対多
  
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  # followingsはここで命名。followingクラスはないため補足説明
  # relationshipsモデルのfollow_idカラム(参照先idはfollowだよ)から、フォローしているUserたちを取得
  # こうすることで、呼び出し側のusers_controllerで user.followings でUserの取得が可能になる(簡単な方法)
  has_many :reverses_of_relationship, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverses_of_relationship, source: :user
  
  has_many :favorites
  has_many :favoritings, through: :favorites, source: :newmicropost
  # ユーザモデルからみた「お気に入り」の定義
  # データの関連性を表すもの＝アソシエーション（関連）の定義
  
  def follow(other_user)
    unless self == other_user
    # もしAさん本人じゃなかったら
      self.relationships.find_or_create_by(follow_id: other_user.id)
      # followの重複を防ぐ
    end
  end
  
  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
    # もしフォローしてたら、アンフォローする
  end
  
  def following?(other_user)
    self.followings.include?(other_user)
    # AさんがフォローしているUserを探す・include?(other_user)Bさんとか他ユーザのものが含まれてないか確認
  end
  
  def feed_newmicroposts
    Newmicropost.where(user_id: self.following_ids + [self.id])
    # following_ids///has_many :followings, から自動生成
    # self.id///データ型を合わせるため配列にして[self.id]
    # Micropost.where(user_id: フォローユーザ + [自分自身]) となる Micropost を全て取得する
  end
  
  # def favorites_list
  #   Newmicroposts.where(user_id: self.favoriting_ids + [self.id])
  # end
  
  def favorite(newmicropost)
    self.favorites.find_or_create_by(newmicropost_id: newmicropost.id)
  end
  
  def unfavorite(newmicropost)
    favorite = self.favorites.find_by(newmicropost_id: newmicropost.id)
    favorite.destroy if favorite
  end
  # newmicropost_idカラム の newmicropost.id を探す
  # 現状は存在していないものを探すので (newmicropost) という風に引数で渡す
  
  def favoriting?(newmicropost)
    self.favoritings.include?(newmicropost)
  end
  #お気に入りしているnewmicropost達を取得
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show, :followings, :followers, :favoritings]
  def index
    @users = User.all.page(params[:page])
    #全ユーザの一覧表示を代入してviewに渡す
    #ページネーション適用のため.page(params[:page])
  end

  def show
   @user = User.find(params[:id])
   @newmicroposts = @user.newmicroposts.order('created_at DESC').page(params[:page])
   counts(@user)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to @user
      # users#showアクションへ強制的に移動
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
      # users/new.html.erb を表示する
    end
  end
  
  def followings
    @user = User.find(params[:id])
    @followings = @user.followings.page(params[:page])
    counts(@user)
  end
  
  def followers
    @user = User.find(params[:id])
    @followers = @user.followers.page(params[:page])
    counts(@user)
  end
  
  def favoritings
    @user = User.find(params[:id])
    @favoritings = @user.favoritings.page(params[:page])
    counts(@user)
    # application_controllerの def counts を利用する
  end
    
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  end
end

#最後のURLを返す。#最後のURLの埋め込み変数　gravatar_id(user.email.downcaseしたものを暗号化) と size 

app/views/users/_users.html.erb
<!--#フォロー・フォロワー表示のため、パーシャル-->
<% if users.any? %>
<!--フォローユーザがいるかどうか。いれば表示-->
  <ul class="media-list">
    <% users.each do |user| %>
      <li class="media">
        <div class="media-left">
          <img class="media-object img-rounded" src="<%= gravatar_url(user, { size: 50 }) %>" alt="">
          <!--アバター定義をhelperに記載　コマンドrails g helper users-->
        </div>
        <div class="media-body">
          <div>
            <%= user.name %>
          </div>
          <div>
            <p><%= link_to 'View profile', user_path(user) %></p>
            <!--user詳細へのリンク-->
          </div>
        </div>
      </li>
    <% end %>
  </ul>
  <%= paginate users %>
<% end %>

app/views/users/favoritings.html.erb
<div class="row">
  <aside class="col-xs-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= @user.name %></h3>
      </div>
      <div class="panel-body">
        <img class="media-object img-rounded img-responsive" src="<%= gravatar_url(@user, { size: 500 }) %>" alt="">
      </div>
    </div>
    <%= render 'relationships/follow_button', user: @user %>
  </aside>
  <div class="col-xs-8">
    <ul class="nav nav-tabs nav-justified">
      <li class="<%= 'active' if current_page?(user_path(@user)) %>"><%= link_to user_path(@user) do %>NewMicroposts <span class="badge"><%= @count_newmicroposts %></span><% end %></li>
      <li class="<%= 'active' if current_page?(followings_user_path(@user)) %>"><%= link_to followings_user_path(@user) do %>Followings <span class="badge"><%= @count_followings %></span><% end %></li>
      <li class="<%= 'active' if current_page?(followers_user_path(@user)) %>"><%= link_to followers_user_path(@user) do %>Followers <span class="badge"><%= @count_followers %></span><% end %></li>
      <li class="<%= 'active' if current_page?(favoritings_user_path(@user)) %>"><%= link_to favoritings_user_path(@user) do %>Favoritings <span class="badge"><%= @count_favoritings %></span><% end %></li>
    </ul>
    
    <!--current_userが登録した「お気に入り」を表示-->
    <!--対応するcontroller//users_controllerで定義した favoritings(def favoritings)をここで順次取り出し-->
    <!--:対応しているusers_controllerで(配列で)定義した@favoritingsはあるか？あれば１つずつ取り出し-->
    <!--パーシャルを介さずにcontrollerの@favoritingsをそのまま使う-->
    <% if @favoritings.any? %>
      <ul class="media-list">
        <% @favoritings.each do |newmicropost| %>
          <li class="media">
            <div class="media-left">
              <img class="media-object img-rounded" src="<%= gravatar_url(@user, { size: 50 }) %>" alt="">
                                                    <!--users_controllerの@userを呼び出す(current_user)-->
            </div>
            <div class="media-body">
              <div>
                <%= link_to newmicropost.user.name, user_path(newmicropost.user) %> <span class="text-muted">posted at <%= newmicropost.created_at %></span>
                <!-- 一対多 投稿に紐づけられたユーザを呼び出す newmicropost.user 投稿者本人の詳細ページへのリンク-->
                <!--app/models/micropost.rb///belongs_to :user  &  app/models/user.rb///has_many :micropostsによって-->
                <!--：このnewmicropostインスタンスを持っているUserを取得可能となる-->
              </div>
              <div>
                <p><%= newmicropost.content %></p>
              </div>
              <span class="col-xs-7 col-sm-3 col-lg-2">
                <%= render 'favorites/favorite_button', newmicropost: newmicropost %>
              </span>
            </div>
          </li>
        <% end %>
      </ul>
      <%= paginate @favoritings %>
      <!--どこの 子要素なのか要確認-->
    <% end %>
  </div>
</div>

app/views/users/followers.html.erb
<div class="row">
  <aside class="col-xs-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= @user.name %></h3>
      </div>
      <div class="panel-body">
        <img class="media-object img-rounded img-responsive" src="<%= gravatar_url(@user, { size: 500 }) %>" alt="">
      </div>
    </div>
    <%= render 'relationships/follow_button', user: @user %>
  </aside>
  <div class="col-xs-8">
    <ul class="nav nav-tabs nav-justified">
      <li class="<%= 'active' if current_page?(user_path(@user)) %>"><%= link_to user_path(@user) do %>NewMicroposts <span class="badge"><%= @count_newmicroposts %></span><% end %></li>
      <li class="<%= 'active' if current_page?(followings_user_path(@user)) %>"><%= link_to followings_user_path(@user) do %>Followings <span class="badge"><%= @count_followings %></span><% end %></li>
      <li class="<%= 'active' if current_page?(followers_user_path(@user)) %>"><%= link_to followers_user_path(@user) do %>Followers <span class="badge"><%= @count_followers %></span><% end %></li>
      <li class="<%= 'active' if current_page?(favoritings_user_path(@user)) %>"><%= link_to favoritings_user_path(@user) do %>Favoritings <span class="badge"><%= @count_favoritings %></span><% end %></li>
    </ul>
    <%= render 'users', users: @followers %>
  </div>
</div>

app/views/users/followings.html.erb
<div class="row">
  <aside class="col-xs-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= @user.name %></h3>
      </div>
      <div class="panel-body">
        <img class="media-object img-rounded img-responsive" src="<%= gravatar_url(@user, { size: 500 }) %>" alt="">
      </div>
    </div>
    <%= render 'relationships/follow_button', user: @user %>
  </aside>
  <div class="col-xs-8">
    <ul class="nav nav-tabs nav-justified">
      <li class="<%= 'active' if current_page?(user_path(@user)) %>"><%= link_to user_path(@user) do %>NewMicroposts <span class="badge"><%= @count_newmicroposts %></span><% end %></li>
      <li class="<%= 'active' if current_page?(followings_user_path(@user)) %>"><%= link_to followings_user_path(@user) do %>Followings <span class="badge"><%= @count_followings %></span><% end %></li>
      <li class="<%= 'active' if current_page?(followers_user_path(@user)) %>"><%= link_to followers_user_path(@user) do %>Followers <span class="badge"><%= @count_followers %></span><% end %></li>
      <li class="<%= 'active' if current_page?(favoritings_user_path(@user)) %>"><%= link_to favoritings_user_path(@user) do %>Favoritings <span class="badge"><%= @count_favoritings %></span><% end %></li>

    </ul>
    <%= render 'users', users: @followings %>
    <!--パーシャル（_users.html.erb）の呼び出し users変数に@followingsを入れてパーシャルに渡している-->
  </div>
</div>

app/views/users/index.html.erb
<%= render 'users', users: @users %>
<!--#フォロー・フォロワー表示のため、パーシャル呼び出し-->

app/views/users/new.html.erb
<!--新しいユーザの入力フォーム-->
<div class="text-center">
  <h1>Sign up</h1>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    
    <%= form_for(@user) do |f| %>
    
      <%= render 'layouts/error_messages', model: f.object %>
      <!--f.objectは@userが代入されている-->
    
    <div class="form-group">
      <%=f.label :name, 'Name' %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
    
    <div class="form-group">
      <%=f.label :email, 'Email' %>
      <%= f.email_field :email, class: 'form-control' %>
    </div>
    
    <div class="form-group">
      <%=f.label :password, 'Password' %>
      <%= f.password_field :password, class: 'form-control' %>
    </div>
    
    <div class="form-group">
      <%=f.label :password_confirmation, 'Confirmation' %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
    </div>
    
    <%= f.submit 'Sing up', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-xs-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= @user.name %></h3>
      </div>
      <div class="panel-body">
        <img class="media-object img-rounded img-responsive" src="<%= gravatar_url(@user, { size: 500 }) %>" alt="">
      </div>
    </div>
    <!--フォローボタン-->
    <%= render 'relationships/follow_button', user: @user %>
  </aside>
  <div class="col-xs-8">
    <ul class="nav nav-tabs nav-justified">
      <li class="<%= 'active' if current_page?(user_path(@user)) %>"><%= link_to user_path(@user) do %>NewMicroposts <span class="badge"><%= @count_newmicroposts %></span><% end %></li>
      <li class="<%= 'active' if current_page?(followings_user_path(@user)) %>"><%= link_to followings_user_path(@user) do %>Followings <span class="badge"><%= @count_followings %></span><% end %></li>
      <li class="<%= 'active' if current_page?(followers_user_path(@user)) %>"><%= link_to followers_user_path(@user) do %>Followers <span class="badge"><%= @count_followers %></span><% end %></li>
      <li class="<%= 'active' if current_page?(favoritings_user_path(@user)) %>"><%= link_to favoritings_user_path(@user) do %>Favoritings <span class="badge"><%= @count_favoritings %></span><% end %></li>
    </ul>
    <%= render 'newmicroposts/newmicroposts', newmicroposts: @newmicroposts %>
  </div>
</div>